# Generated by Django 4.2.3 on 2023-08-09 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothingstore', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='colors',
        ),
        migrations.AddField(
            model_name='product',
            name='colors',
            field=models.ManyToManyField(to='clothingstore.color'),
        ),
    ]
