# Generated by Django 4.2.3 on 2023-08-09 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clothingstore', '0003_subcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='available_sizes',
        ),
    ]
